env: sc2

sum_keys: [return, reward_positive]
last_keys: [battle_won, dead_allies, dead_enemies, ep_length]
mean_keys: []

env_args:
  map_name: "4m_vs_3m"
  obs_agent_id: True
  state_agent_id: True
  death_masking: False
  continuing_episode: False
  difficulty: "7"
  game_version: null
  move_amount: 2
  obs_all_health: True
  obs_instead_of_state: False
  obs_last_action: False
  obs_own_health: True
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_timestep_number: False
  reward_death_value: 10
  reward_defeat: -200
  reward_negative_scale: 1
  reward_only_positive: False
  reward_scale: True
  reward_scale_rate: 20
  reward_sparse: False
  reward_win: 200
  replay_dir: "./xrx_videos/"
  replay_prefix: ""
  state_last_action: True
  state_timestep_number: False
  step_mul: 8
  heuristic_ai: False
  heuristic_rest: False
  debug: False
